### ISSUE TITLE
How to?

### ISSUE THREAD

**Issue by vittore** [nicolocarpignoli/artoolkit-barcode-markers-collection#1]
Hi,

thanks for your efforts on AR. A newbie question: to use this collections of markers with ar.js e.g. AR_MATRIX_CODE_4x4_BCH_13_5_5 what is the correct syntax?

```
<a-scene embedded arjs='sourceType: webcam; debugUIEnabled: false; detectionMode: mono_and_matrix; matrixCodeType: 4x4;'>
```

So minimal code is:

```
<!doctype HTML>
<html>
<head>
    <meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
</head>
<script src="https://aframe.io/releases/1.0.4/aframe.min.js"></script>
    <script src="https://raw.githack.com/AR-js-org/AR.js/master/aframe/build/aframe-ar.js"></script>
<script src="https://rawgit.com/donmccurdy/aframe-extras/master/dist/aframe-extras.loaders.min.js"></script>


</head>
<body style='margin : 0px; overflow: hidden;'>
<a-scene embedded arjs='sourceType: webcam; debugUIEnabled: false; detectionMode: mono_and_matrix; matrixCodeType: 4x4;'>

    <a-marker type='barcode' value='3'>
        <a-box position='0 0.5 0' color="yellow"></a-box>
    </a-marker>

    <a-marker id="animated-marker" type='barcode' value='1'>
        <a-box position='0 0.5 0' color="red"></a-box>
    </a-marker>


    <a-entity camera></a-entity>
</a-scene>
</body>
</html>
```

Thanks in advance.
V.

**Comment by jacklynlxq** [comment]
> Hi,
> 
> thanks for your efforts on AR. A newbie question: to use this collections of markers with ar.js e.g. AR_MATRIX_CODE_4x4_BCH_13_5_5 what is the correct syntax?
> 
> ```
> <a-scene embedded arjs='sourceType: webcam; debugUIEnabled: false; detectionMode: mono_and_matrix; matrixCodeType: 4x4;'>
> ```
> 
> So minimal code is:
> 
> ```
> <!doctype HTML>
> <html>
> <head>
>     <meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
> </head>
> <script src="https://aframe.io/releases/1.0.4/aframe.min.js"></script>
>     <script src="https://raw.githack.com/AR-js-org/AR.js/master/aframe/build/aframe-ar.js"></script>
> <script src="https://rawgit.com/donmccurdy/aframe-extras/master/dist/aframe-extras.loaders.min.js"></script>
> 
> 
> </head>
> <body style='margin : 0px; overflow: hidden;'>
> <a-scene embedded arjs='sourceType: webcam; debugUIEnabled: false; detectionMode: mono_and_matrix; matrixCodeType: 4x4;'>
> 
>     <a-marker type='barcode' value='3'>
>         <a-box position='0 0.5 0' color="yellow"></a-box>
>     </a-marker>
> 
>     <a-marker id="animated-marker" type='barcode' value='1'>
>         <a-box position='0 0.5 0' color="red"></a-box>
>     </a-marker>
> 
> 
>     <a-entity camera></a-entity>
> </a-scene>
> </body>
> </html>
> ```
> 
> Thanks in advance.
> V.

I'm no expert but I followed the [documentation ](https://ar-js-org.github.io/AR.js-Docs/marker-based/) and it works in my application. So if you're asking for the values of ```matrixCodeType```, it should be one of them in [3x3, 3x3_HAMMING63, 3x3_PARITY65, 4x4, 4x4_BCH_13_9_3, 4x4_BCH_13_5_5]. So ```matrixCodeType: 4x4_BCH_13_5_5;``` in your case. Although I'm not sure if we can use the 5x5 barcode provided in this repo since in this as mentioned in this [issue](https://github.com/jeromeetienne/AR.js/issues/509#issuecomment-583317853).

**Comment by nicolocarpignoli** [comment]
Updated the repo. Please check new files and updated Readme.
