### ISSUE TITLE
The markers should not be called "barcode markers". Maybe call it "QR or grid markers" instead. 

### ISSUE THREAD

**Issue by felixniemeyer** [nicolocarpignoli/artoolkit-barcode-markers-collection#4]
Barcodes are codes made up of bars. Often vertical bars with different thicknesses and distances. Here is an example: 
![image](https://user-images.githubusercontent.com/5720176/215992162-edb294e3-0265-469c-812a-2c71c904724b.png)

I can see no barcodes in this repository. 

Maybe call it "QR markers", because it resembles QR codes. 
Or call it "grid markers".

**Comment by nicolocarpignoli** [comment]
Hi there,

you're right about the "barcode" word alone. With "barcode" I have used a short version for "2D-barcode", aka "two dimensional barcodes", initially introduced [here](https://github.com/nicolocarpignoli/artoolkit-docs/blob/master/3_Marker_Training/marker_barcode.md).

Anyway, I never call them "barcodes" alone, but "barcode markers". Change the name to "QR code" is instead misleading as people might think it's okay to use a QR Code app to scan them, while it's not.

**Comment by felixniemeyer** [comment]
I agree that "QR marker" is misleading as well. 

"2D barcode" makes no sense in my opinion because there are still no bars. 
But I realized "2D barcode" is the term that has become established for it.

I prefer "2D code" or "2D marker" or "matrix code" or "matrix marker".
